### PR TITLE
More Swal changes

### PR DESCRIPTION
**Pull request by KenyanGeek**

### CODE REVIEW

**Comment by nyugoh** [comment]
I have tested the new changes, seems to be looking working well. Let's :rocket:

**Comment by KenyanGeek** [comment]
Cool beans!!

Herman Njoroge Chege

Phone:+254 721 733354
Skype: herman.njoroge1

**Comment by nyugoh** [comment]
Cool beans...??? :question:

**Comment by nyugoh** [comment]
I have sent an invitation to add you as a collaborator.

**Comment by nyugoh** [comment]
Am connecting now to sqlite, the php part is done.

**Comment by nyugoh** [comment]
Initial setup modal has a higher z-index than the swal.
screenshot at 2018-02-19 10-09-50

**Pull request merged**
